version: '3.8'

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/
    restart: always
    depends_on:
      - wordpress



networks:
  inception:
    driver: bridge
